# SPDX-License-Identifier: MIT-0
---
- name: 安裝
  block:
    - name: 安裝依賴 (Ubuntu)
      ansible.builtin.apt:
        name:
          - liblz4-dev
          - postgresql-server-dev-{{ pg_version | int }}
        update_cache: true
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: 安裝依賴 (Rocky)
      ansible.builtin.yum:
        name:
          - lz4-devel
          - postgresql{{ pg_version | int }}-devel
        state: present
      when: ansible_distribution == "Rocky"

    - name: 下載源碼
      ansible.builtin.get_url:
        url: https://api.pgxn.org/dist/pg_repack/{{ pg_repack_version }}/pg_repack-{{ pg_repack_version }}.zip
        dest: "/usr/local/src/"
        owner: root
        group: root
        mode: "0755"

    - name: 解壓縮源碼
      ansible.builtin.unarchive:
        src: "/usr/local/src/pg_repack-{{ pg_repack_version }}.zip"
        dest: "/usr/local/src/"
        remote_src: true

    - name: 編譯 & 安裝
      ansible.builtin.shell:
        cmd: make PG_CONFIG=/usr/local/pgsql/bin/pg_config && make PG_CONFIG=/usr/local/pgsql/bin/pg_config install
        chdir: "/usr/local/src/pg_repack-{{ pg_repack_version }}"
        executable: /bin/bash
      changed_when: false

    - name: 把 VACUUM 腳本上傳
      ansible.builtin.copy:
        src: p_vacuum.sh
        dest: "/usr/local/bin"
        owner: postgres
        group: postgres
        mode: "0700"
