---
- name: 設定歸檔模式
  block:
    - name: 設定歸檔參數
      ansible.builtin.template:
        src: pg_archive.conf
        dest: /var/lib/pgsql/data/conf.d
        owner: postgres
        group: postgres
        mode: "0700"

    - name: 上傳歸檔腳本
      ansible.builtin.template:
        src: pg_archive_wal.sh
        dest: /usr/local/bin
        owner: postgres
        group: postgres
        mode: "0700"
