- name: 變更 conf 檔案，引入 ./conf.d 目錄
  ansible.builtin.lineinfile:
    path: "/var/lib/pgsql/data/postgresql.conf"
    regexp: '^#include_dir'
    line: "include_dir='conf.d'"
    backup: true
    state: present

- name: 建立 conf.d 目錄
  ansible.builtin.file:
    path: /var/lib/pgsql/data/conf.d
    state: directory
    owner: postgres
    group: postgres
    mode: "0700"

- name: 上傳 conf 檔案
  ansible.builtin.template:
    src: pg_base.conf
    dest: /var/lib/pgsql/data/conf.d/pg_base.conf
    owner: postgres
    group: postgres
    mode: "0700"

- name: 上傳日誌設定 conf 檔案
  ansible.builtin.copy:
    src: log.conf
    dest: /var/lib/pgsql/data/conf.d/log.conf
    owner: postgres
    group: postgres
    mode: "0700"

- name: 上傳歸檔腳本
  ansible.builtin.template:
    src: pg_archive_wal.sh
    dest: /usr/local/bin
    owner: postgres
    group: postgres
    mode: "0700"

- name: 設定歸檔參數
  ansible.builtin.template:
    src: pg_archive.conf
    dest: /var/lib/pgsql/data/conf.d
    owner: postgres
    group: postgres
    mode: "0700"
